"""Herdr operation protocols required by task lifecycle policy."""

from pathlib import Path
from typing import Protocol

from herdr_runtime import CreatedResources, PaneInfo, TabInfo, WorkspaceInfo


class HerdrOperations(Protocol):
    """Mutating operations required by task startup."""

    def workspace_get(self, workspace_id: str) -> WorkspaceInfo: ...
    def workspace_create(self, label: str, cwd: Path) -> CreatedResources: ...
    def workspace_close(self, workspace_id: str) -> None: ...
    def tab_get(self, tab_id: str) -> TabInfo: ...
    def tab_create(self, workspace_id: str, label: str, cwd: Path) -> CreatedResources: ...
    def tab_rename(self, tab_id: str, label: str) -> TabInfo: ...
    def tab_close(self, tab_id: str) -> None: ...
    def panes_for_workspace(self, workspace_id: str, tab_id: str) -> list[PaneInfo]: ...


class HerdrPlanningOperations(Protocol):
    """Read-only Herdr operations required by cleanup planning."""

    def workspace_find(self, workspace_id: str) -> WorkspaceInfo | None: ...
    def tab_find(self, tab_id: str) -> TabInfo | None: ...
